-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc/untitled/untitled.vhd
-- Created: 2016-11-13 21:16:39
-- 
-- Generated by MATLAB 8.1 and HDL Coder 3.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 0
-- Target subsystem base rate: inf
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: untitled
-- Source Path: untitled
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY untitled IS
END untitled;


ARCHITECTURE rtl OF untitled IS

  -- Signals
  SIGNAL Sine_Wave_Function_out1          : real := 0.0;  -- double
  SIGNAL TmpGroundAtSine_Wave_Function1Inport1_out1 : real := 0.0;  -- double
  SIGNAL Sine_Wave_Function1_out1         : real := 0.0;  -- double

BEGIN


  TmpGroundAtSine_Wave_Function1Inport1_out1 <= 0.0;


END rtl;

