clc; clear;
close all;
data1=2*rand(1,500)+2;
data2=randn(1,500)+3;
subplot(2,1,1),hist(data1,25),...
    title('Histogram of data1'),...
    xlabel('x'),...
    ylabel('N'),...
    subplot(2,1,2),hist(data2,25),...
    title('Histogram of data2'),...
    xlabel('x'),...
    ylabel('N')