%3d plot
x=-2:0.1:2;
y=-1:0.1:2;
[X,Y]=meshgrid(x,y);
Z=Y.*exp(-(X.^2+Y.^2));
subplot(2,1,1), mesh(X,Y,Z),...
		title('Mesh Plot'), xlabel('x'),...
		ylabel('y'),zlabel('z'),...
		subplot(2,1,2),surf(X,Y,Z),...
		title('Surface Plot'), xlabel('x'),...
		ylabel('y'), xlabel('z')