%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Author: Mathan Kumar Moorthy
% Organization: ASU - PhotoVoltaic Reliability Laboratory
% Date: 11/04/2015
% Code details: This code is used for  
% importing performance defects visual inspection 
% data
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function tableout = importfile10(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE10 Import data from a spreadsheet
%   IMPORTFILE10(FILE) reads data from the first worksheet in the Microsoft
%   Excel spreadsheet file named FILE and returns the data as a table.
%
%   IMPORTFILE10(FILE,SHEET) reads from the specified worksheet.
%
%   IMPORTFILE10(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   importfile10('VI.xlsx','Sheet1',2,745);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2015/08/03 21:39:26

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 2;
    endRow = 2000;
end

%% Import the data
[~, ~, raw1] = xlsread(workbookFile, sheetName, sprintf('A%d:C%d',startRow(1),endRow(1)));
[~, ~, raw2] = xlsread(workbookFile, sheetName, sprintf('E%d:E%d',startRow(1),endRow(1)));
[~, ~, raw3] = xlsread(workbookFile, sheetName, sprintf('G%d:I%d',startRow(1),endRow(1)));
[~, ~, raw4] = xlsread(workbookFile, sheetName, sprintf('L%d:P%d',startRow(1),endRow(1)));
[~, ~, raw5] = xlsread(workbookFile, sheetName, sprintf('V%d:Z%d',startRow(1),endRow(1)));
[~, ~, raw6] = xlsread(workbookFile, sheetName, sprintf('AB%d:AB%d',startRow(1),endRow(1)));
[~, ~, raw7] = xlsread(workbookFile, sheetName, sprintf('AG%d:AG%d',startRow(1),endRow(1)));
[~, ~, raw8] = xlsread(workbookFile, sheetName, sprintf('AI%d:AO%d',startRow(1),endRow(1)));
[~, ~, raw9] = xlsread(workbookFile, sheetName, sprintf('AS%d:AS%d',startRow(1),endRow(1)));
[~, ~, raw10] = xlsread(workbookFile, sheetName, sprintf('AY%d:BO%d',startRow(1),endRow(1)));
[~, ~, raw11] = xlsread(workbookFile, sheetName, sprintf('BQ%d:BX%d',startRow(1),endRow(1)));
[~, ~, raw12] = xlsread(workbookFile, sheetName, sprintf('BZ%d:CI%d',startRow(1),endRow(1)));
raw = [raw1,raw2,raw3,raw4,raw5,raw6,raw7,raw8,raw9,raw10,raw11,raw12];
for block=2:length(startRow)
    [~, ~, tmpRawBlock1] = xlsread(workbookFile, sheetName, sprintf('A%d:C%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock2] = xlsread(workbookFile, sheetName, sprintf('E%d:E%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock3] = xlsread(workbookFile, sheetName, sprintf('G%d:I%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock4] = xlsread(workbookFile, sheetName, sprintf('L%d:P%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock5] = xlsread(workbookFile, sheetName, sprintf('V%d:Z%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock6] = xlsread(workbookFile, sheetName, sprintf('AB%d:AB%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock7] = xlsread(workbookFile, sheetName, sprintf('AG%d:AG%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock8] = xlsread(workbookFile, sheetName, sprintf('AI%d:AO%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock9] = xlsread(workbookFile, sheetName, sprintf('AS%d:AS%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock10] = xlsread(workbookFile, sheetName, sprintf('AY%d:BO%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock11] = xlsread(workbookFile, sheetName, sprintf('BQ%d:BX%d',startRow(block),endRow(block)));
    [~, ~, tmpRawBlock12] = xlsread(workbookFile, sheetName, sprintf('BZ%d:CI%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock1,tmpRawBlock2,tmpRawBlock3,tmpRawBlock4,tmpRawBlock5,tmpRawBlock6,tmpRawBlock7,tmpRawBlock8,tmpRawBlock9,tmpRawBlock10,tmpRawBlock11,tmpRawBlock12]; %#ok<AGROW>
end
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,1);
raw = raw(:,[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62]);

%% Create output variable
I = cellfun(@(x) ischar(x), raw);
raw(I) = {NaN};
data = reshape([raw{:}],size(raw));

%% Create table
tableout = table;

%% Allocate imported array to column variable names
tableout.Module = cellVectors(:,1);
tableout.Frontglasslightlysoiled = data(:,1);
tableout.Frontglassheavilysoiled = data(:,2);
tableout.Frontglasscrazing = data(:,3);
tableout.Frontglasschip = data(:,4);
tableout.Frontglassmilkydiscoloration = data(:,5);
tableout.Rearglasscrazing = data(:,6);
tableout.Rearglasschipped = data(:,7);
tableout.Edgesealdelamination = data(:,8);
tableout.Edgesealmoisturepenetration = data(:,9);
tableout.Edgesealdiscoloration = data(:,10);
tableout.Edgesealsqueezedpinchedout = data(:,11);
tableout.Framebent = data(:,12);
tableout.Framediscoloration = data(:,13);
tableout.Frameadhesivedegraded = data(:,14);
tableout.Frameadhesiveoozedout = data(:,15);
tableout.Frameadhesivemissinginareas = data(:,16);
tableout.BypassdiodeshortcircuitEquipmentneeded = data(:,17);
tableout.Junctionboxlidloose = data(:,18);
tableout.Junctionboxwarped = data(:,19);
tableout.Junctionboxweathered = data(:,20);
tableout.Junctionboxadhesiveloose = data(:,21);
tableout.Junctionboxadhesivefelloff = data(:,22);
tableout.Junctionboxwireattachmentsloose = data(:,23);
tableout.Junctionboxwireattachmentsfelloff = data(:,24);
tableout.Junctionboxwireattachmentsarced = data(:,25);
tableout.Wirescorroded = data(:,26);
tableout.Backsheetwavy = data(:,27);
tableout.Backsheetdiscoloration = data(:,28);
tableout.Backsheetbubble = data(:,29);
tableout.Gridlinediscoloration = data(:,30);
tableout.Gridlineblossoming = data(:,31);
tableout.Busbardiscoloration = data(:,32);
tableout.Busbarcorrosion = data(:,33);
tableout.Busbarburnmarks = data(:,34);
tableout.Busbarmisaligned = data(:,35);
tableout.CellInterconnectribbondiscoloration = data(:,36);
tableout.CellInterconnectribboncorrosion = data(:,37);
tableout.CellInterconnectribbonburnmark = data(:,38);
tableout.CellInterconnectribbonbreak = data(:,39);
tableout.StringInterconnectdiscoloration = data(:,40);
tableout.StringInterconnectcorrosion = data(:,41);
tableout.StringInterconnectburnmark = data(:,42);
tableout.StringInterconnectbreak = data(:,43);
tableout.Celldiscoloration = data(:,44);
tableout.CellburnMark = data(:,45);
tableout.Cellchippingcrack = data(:,46);
tableout.Cellmoisturepenetration = data(:,47);
tableout.CellwormmarkSnailTracks = data(:,48);
tableout.Cellforeignparticleembedded = data(:,49);
tableout.Interconnectdiscoloration = data(:,50);
tableout.SolderbondFatigueFailureEquipmentneeded = data(:,51);
tableout.Hotspotlessthan20CEquipmentneeded = data(:,52);
tableout.Encapsulantdelaminationoverthecell = data(:,53);
tableout.Encapsulantdelaminationunderthecell = data(:,54);
tableout.Encapsulantdelaminationoverthejunctionbox = data(:,55);
tableout.Encapsulantdelaminationnearinterconnectorfingers = data(:,56);
tableout.Encapsulantdiscolorationyellowingbrowning = data(:,57);
tableout.ThinFilmModuleDiscoloration = data(:,58);
tableout.ThinFilmModuleDelaminationAbsorberTCOlayer = data(:,59);
tableout.ThinFilmModuleDelaminationARcoating = data(:,60);
tableout.Modulemismatch = data(:,61);

